#!/bin/bash

if [[ $EUID != 0 ]]; then
    echo "Please run as root"
    exit
fi

folder_name=$1
url=$2

# fail if we don't get at least one input
if [[ $folder_name = "" ]]; then
  echo 'No folder name was specified'
  exit 1;
fi

if [[ $url = "" ]]; then
  url=$folder_name
fi

cd /hdd/docker

# creates the folder
sudo -u $SUDO_USER mkdir $folder_name
# copies the template file
sudo -u $SUDO_USER cp docker-compose-default.yml $folder_name/docker-compose.yml
cd $folder_name

mkdir public
chown $SUDO_USER:www-data -R public/
chmod 775 -R public/

mkdir html
chown $SUDO_USER:www-data -R html/
chmod 775 -R html/

# replaces placeholders
sudo -u $SUDO_USER sed -i "s/NAME/$folder_name/g" docker-compose.yml
sudo -u $SUDO_USER sed -i "s/URL/$url/g" docker-compose.yml

# add to hosts
echo "127.0.0.1 $url.dev  www.$url.dev" >> /etc/hosts

# echo out results
echo "Created a new docker instance in folder: $folder_name"
echo "With containers prefixed with $folder_name"
echo "With the url of: $url.dev"

